# Deploy Website Theme
# This workflow handles building and deploying the website theme

name: Deploy Website Theme 

on:
  push: 
    branches:
      - main

# Environment variables for reuse  
env:
  SERVER: root@myhs.mooo.com
  REMOTE_DIR: /mydir/wp-content/themes/mytheme

jobs:

  # Build job
 build:  
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      # Check out repository code
      uses: actions/checkout@v3
    - name: Cache dependencies
      # Cache Node modules for faster builds   
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    - name: Install PHP dependencies
      # Install PHP dependencies with Composer
      uses: php-actions/composer@v6
    - name: Setup Node.js
      # Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
    - name: Install NPM dependencies
      # Install NPM dependencies from lock file  
      run: npm ci
    - name: Build theme
      # Build theme static assets
      run: npm run build
  # Deploy job  
 deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    
    - name: Checkout code
      # Check out repository code
      uses: actions/checkout@v3

    - name: Deploy to server
      # Deploy built assets to server over SSH
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
        
        rsync -ravz -e "ssh -o StrictHostKeyChecking=no" ./theme/ ${{ env.SERVER }}:${{ env.REMOTE_DIR }}